Feature/login (초기세팅에 있던 app.js 기본 구성까지 함께 올렸습니다)
wecode-bootcamp-korea/49-2nd-ABC-Martens-backend pull request #8
Opened 2023-09-22 09:50 UTC by DeveloperPMYJ

## 1. 본 PR이 우리 팀의 웹 서비스 제품성에 어떠한 기여를 하였고, <br> 사용자에게 어떠한 기대효과를 전달하는지 작성해주세요.

- 내 PR이 제품 내 어떠한 기능적인 배경/전후맥락 가운데 개발되었나요?

회원가입 후 로그인을 위한 기능 

- 내 PR이 Merge 됨으로써 유저에게 전달되는 편익/기대효과는 무엇일까요?

로그인을 통해 상품목록 확인, 장바구니 기능 이용, 주문 및 결제까지 이어지는 기대효과

<br />

## 2. 이 브랜치에서 어떤 내용을 개발했는지 큰 제목과 상세 내역을 적어주세요.

- 회원가입을 한 유저 database에서, 기입한 이메일 주소와 비교 후, 회원가입한 유저인지 판별.
- 판별 후, 회원가입을 한 유저만 로그인을 하고, 리뷰를 작성할 수 있도록  커뮤니티 관리를 하는 안전장치
- 고객의 주문 및 결제 시, 유저의 정보를 갖고 있는 회원가입한 유저만 가능하도록 함으로써, 이후 발생할 수 있는 리스크에 데이터베이스에 보유하고 있는 고객 정보를 바탕으로 리스크 관리 및 고객관리
- 해쉬화된 비밀번호를 DB에서 가져와서 비교 후 토큰 발급 

이후 이 토큰은 리뷰 작성, 주문 및 결제에 토큰을 통해 회원가입한 유저인지 확인하는 기능을 하게 될 것입니다. 

<br />

## 3. 개발한 화면을 캡쳐해서 첨부 해 주세요. 
<br />

<img width="607" alt="스크린샷 2023-09-22 오후 6 40 04" src="https://github.com/wecode-bootcamp-korea/49-2nd-ABC-Martens-backend/assets/142304129/7803f118-f5fd-4082-bafb-175dfbf0731c">
<img width="646" alt="스크린샷 2023-09-22 오후 6 40 36" src="https://github.com/wecode-bootcamp-korea/49-2nd-ABC-Martens-backend/assets/142304129/5ef3930f-dfa3-4cdf-a2a2-1c8cb0dbad5e">
<img width="669" alt="스크린샷 2023-09-22 오후 6 40 56" src="https://github.com/wecode-bootcamp-korea/49-2nd-ABC-Martens-backend/assets/142304129/b36e42a5-e703-4896-a661-8a53f1f1a5cc">

<br />

## 4. 이 브랜치에서 개발하면서 느꼈던 개발 성장포인트를 적어주세요.

- 프로젝트 1에서도 놓쳤던, 비밀번호 해쉬화를 다시 익히게 되었다. 
- 회원가입 코드에서, 잊고 비밀번호 해쉬화를 안 했는데, 이번 로그인 코드를 통해서 다시 수정할 수 있는 기회를 가지게 되었다. 

  <br />

2023-09-22 10:07 UTC, 03290419 requested changes

2023-09-22 10:07 UTC, 03290419 commented on app.js
> +const server = http.createServer(app);
89-102번 줄은 이미 app.js에 적혀있는 부분과 models/dataSource.js 파일과 중복되어서 해당 부분만 제거 부탁드려요~! 또한 app.post 는 app.listen 및  app.use((req, _, next) => {
  const error = new Error(`${req.method} ${req.url} 라우터가 없습니다.`);
  error.status = 404;
  next(error);
});
 함수보다 위에 있어야 합니다!

2023-09-22 10:07 UTC, 03290419 commented on app.js
> +});v
요기 오타가 있는 것 같습니당

2023-09-22 10:07 UTC, 03290419 commented on app.js
> +    console.log('existing user:', existingUser);
console.log 는 dev에 머지를 최대한 지양해주세요!

2023-09-22 10:42 UTC, DeveloperPMYJ commented on app.js
> +const server = http.createServer(app);
1) 

app.use((req, _, next) => {
  const error = new Error(`${req.method} ${req.url} 라우터가 없습니다.`);
  error.status = 404;
  next(error);
});

app.use((err, _, res, next) => {
  res.status(err.status || 500);
  return res.json({
    error: `${err.status ? err.status : ''} ${err.message}`,
  });
});   


이거 2개 다 app.post 아래로 가야 하는 게 맞을까요? 

2) 
그리고, port는 8000이 아니라, 변수처리해야할까요

app.listen(app.get('port'), () => {
  console.log(`listening.... 🦻http://localhost:${app.get('port')}`);
});

2023-09-23 07:16 UTC, Park-KJ approved these changes

2023-09-23 07:18 UTC, Park-KJ approved these changes

2023-10-02 06:41 UTC, 03290419 requested changes

2023-10-02 06:41 UTC, 03290419 commented on app.js
> +const server = http.createServer(app);
1. 넵 맞습니다 app.use((req, _, next) => {
const error = new Error(${req.method} ${req.url} 라우터가 없습니다.);
error.status = 404;
next(error);
});

app.use((err, _, res, next) => {
res.status(err.status || 500);
return res.json({
error: ${err.status ? err.status : ''} ${err.message},
});
});  이 두개와 app.listen 구문은 app.js 최하단에 위치해야합니다. 
2.  선언해주신 `start` 함수와  app.listen(app.get('port'), () => {
  console.log(`listening.... 🦻http://localhost:${app.get('port')}`);
}); 는 동작이 똑같습니다. 두개가 공존하면 하나는 불필요한 동작이 되므로 하나는 없어야합니다~ port에 대한 넘버링은 환경이 바뀔것을 대비해 가급적 변수인 편이 좋습니다.

2023-10-02 07:42 UTC, 03290419 approved these changes
확인했습니다!

2023-10-04 12:28 UTC, merged